// Generated by Melange
'use strict';

const Janus__FiniteDomain = require("./FiniteDomain.js");
const Stdlib__Array = require("melange/array.js");

function to_core(d) {
  return {
    universe: Stdlib__Array.to_list(d.universe),
    values: Stdlib__Array.to_list(d.values)
  };
}

function of_core(d) {
  return {
    universe: Stdlib__Array.of_list(d.universe),
    values: Stdlib__Array.of_list(d.values)
  };
}

function isEmpty(d) {
  return Janus__FiniteDomain.FiniteDomain.isEmpty(to_core(d));
}

function isDefinedAt(eqb, d, x) {
  return Janus__FiniteDomain.FiniteDomain.isDefinedAt(eqb, to_core(d), x);
}

function isSubsetOf(eqb, a, b) {
  return Janus__FiniteDomain.FiniteDomain.isSubsetOf(eqb, to_core(a), to_core(b));
}

function isSupersetOf(eqb, a, b) {
  return Janus__FiniteDomain.FiniteDomain.isSupersetOf(eqb, to_core(a), to_core(b));
}

function equals(eqb, a, b) {
  return Janus__FiniteDomain.FiniteDomain.equals(eqb, to_core(a), to_core(b));
}

function union(a, b) {
  return of_core(Janus__FiniteDomain.FiniteDomain.union(to_core(a), to_core(b)));
}

function intersection(eqb, a, b) {
  return of_core(Janus__FiniteDomain.FiniteDomain.intersection(eqb, to_core(a), to_core(b)));
}

function difference(eqb, a, b) {
  return of_core(Janus__FiniteDomain.FiniteDomain.difference(eqb, to_core(a), to_core(b)));
}

function complement(eqb, d) {
  return of_core(Janus__FiniteDomain.FiniteDomain.complement(eqb, to_core(d)));
}

module.exports = {
  to_core,
  of_core,
  isEmpty,
  isDefinedAt,
  isSubsetOf,
  isSupersetOf,
  equals,
  union,
  intersection,
  difference,
  complement,
}
/* No side effect */
